# Generated by Django 4.1.3 on 2022-11-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='desconocido', max_length=30, unique=True)),
                ('cambio_soles', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'monedas',
                'ordering': ['id_p', 'nombre', 'cambio_soles'],
            },
        ),
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='desconocido', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'operadoras',
                'ordering': ['id_p', 'nombre'],
            },
        ),
    ]
