# Generated by Django 4.1.3 on 2022-11-21 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapl', '0002_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='desconocido', max_length=30, unique=True)),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paises', to='mapl.pais')),
            ],
            options={
                'db_table': 'ciudades',
                'ordering': ['id_p', 'nombre'],
            },
        ),
    ]
