# Generated by Django 4.1.3 on 2022-11-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapl', '0003_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='desconocido', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['id_p', 'nombre'],
            },
        ),
    ]
