# Generated by Django 4.1.3 on 2022-11-21 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapl', '0005_mapl'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPublicacion',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='negocios', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'categorias_publicaciones',
                'ordering': ['id_p', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaUsuario',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='normal', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'categorias_usuarios',
                'ordering': ['id_p', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuenta', models.CharField(max_length=15, unique=True)),
                ('numero_tarjeta', models.CharField(max_length=20, unique=True)),
                ('pin', models.CharField(max_length=6)),
                ('moneda_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monedacuenta', to='mapl.moneda')),
            ],
            options={
                'db_table': 'cuentas_bancarias',
                'ordering': ['id_p', 'numero_cuenta'],
            },
        ),
        migrations.CreateModel(
            name='TipoInteres',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='normal', max_length=30, unique=True)),
                ('porcentaje', models.IntegerField()),
            ],
            options={
                'db_table': 'tipos_intereses',
                'ordering': ['id_p', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='deposito', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipos_operaciones',
                'ordering': ['id_p', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='personal', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipos_prestamos',
                'ordering': ['id_p', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoPromocion',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30, unique=True)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'tipos_promociones',
                'ordering': ['id_p', 'cantidad'],
            },
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(default='desconocido', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(default='desconocido', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(default='usuario', max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Jhon Doe', max_length=30)),
                ('apellido', models.CharField(default='Kard', max_length=30)),
                ('direcion', models.CharField(default='39178 Ernser Haven', max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(default='contrasena', max_length=100)),
                ('url_perfil', models.CharField(default='https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1071.jpg', max_length=200)),
                ('ciudad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudadusario', to='mapl.ciudad')),
                ('pais_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paisusuario', to='mapl.pais')),
                ('rol_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='rolusuario', to='mapl.rol')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['id_p', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PublicacionBanco',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Sin Titulo', max_length=150)),
                ('texto', models.TextField()),
                ('url_imagen', models.CharField(default='http://loremflickr.com/640/480/business', max_length=300)),
                ('categoria_publicacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriasid', to='mapl.categoriapublicacion')),
            ],
            options={
                'db_table': 'publicaciones_banco',
                'ordering': ['id_p', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='PromocionDisponibleUsuario',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('cuenta_bancaria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocuentabancarai', to='mapl.cuentabancaria')),
                ('tipo_promocion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociondisponible', to='mapl.tipopromocion')),
            ],
            options={
                'db_table': 'promociones_disponibles_usuarios',
                'ordering': ['id_p'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('cuenta_bancaria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentaprestamo', to='mapl.cuentabancaria')),
                ('tipo_prestamo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoprestamo', to='mapl.tipoprestamo')),
            ],
            options={
                'db_table': 'prestamos',
                'ordering': ['id_p', 'monto'],
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('cuenta_bancaria_destino_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentabancaoperacion', to='mapl.cuentabancaria')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacionoperacion', to='mapl.tipooperacion')),
            ],
            options={
                'db_table': 'operaciones',
                'ordering': ['id_p', 'monto'],
            },
        ),
        migrations.CreateModel(
            name='NumeroTelefono',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('operadora_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numerooperadora', to='mapl.operadora')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numerousuario', to='mapl.usuario')),
            ],
            options={
                'db_table': 'numeros_telefonos',
                'ordering': ['id_p', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentausario', to='mapl.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='Sin comentarios', max_length=300)),
                ('publicacion_banco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacionbancocomentario', to='mapl.publicacionbanco')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuariocomentario', to='mapl.usuario')),
            ],
            options={
                'db_table': 'comentarios',
                'ordering': ['id_p', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='arequipa', max_length=30, unique=True)),
                ('ciudad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudadesAgencia', to='mapl.ciudad')),
                ('pais_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paisesAgencia', to='mapl.pais')),
            ],
            options={
                'db_table': 'agencias',
                'ordering': ['id_p', 'nombre'],
            },
        ),
    ]
